### ISSUE TITLE
identify other recipes

### ISSUE THREAD

**Issue by kampanosg** [kampanosg/bakery#13]
users should be allowed to include other recipes in their `steps` list. for example:

```yaml
recipes:
    build:
        steps:
            - "go build -o app ./..."
    run:
        steps:
            - build
            - ./app
```

the order of the recipes should not matter. so in the above example, if `build` is defined after `run`, it should still work.

**acceptance criteria**
* identify and run other recipes
