### ISSUE TITLE
default recipes

### ISSUE THREAD

**Issue by kampanosg** [kampanosg/bakery#14]
allow users to define a `default` sequence of `recipes`. example syntax:

```yaml
default:
    - test
    - build
    - run
recipes:
    test:
        steps:
            - go test -v ./...
    build:
        steps:
            - go build -o app ./...
    run:
        steps:
            - ./app
```

The `default` sequence should be called only when the user doesn't supply any arguments, for example only runs `bake`

acceptance criteria
* parse the `default` sequence
* execute the recipes
* identify that user wants to run `default`
