### ISSUE TITLE
parse recipes from YAML

### ISSUE THREAD

**Issue by kampanosg** [kampanosg/bakery#3]
The `Recipes` file, should contain a `recipes` list, which allows users to define their custom commands. A valid `recipes` array should look like this:

```yaml
recipes:   
    - run:
        description: "installs all dependencies"
        default: false
        steps:
            - "./run.sh"
```

Each `recipe` has a `steps` list that defines the commands that the recipe will execute once ran

<b>Acceptance Criteria</b>
<ul>
  <li>Parse the above YAML</li>
</ul>
