### ISSUE TITLE
recipes not found when there's spaces before or after the step

### ISSUE THREAD

**Issue by kampanosg** [kampanosg/bakery#36]
it seems that if there's a space before / after a recipe, which is part of a step, it is not found in the recipes map. example:

```yaml
recipes:
  clean:
    steps: 
      - "rm app"
  build:
    steps:
      - "^ clean"
      - "go build -o app"
```

when the `build` recipe runs, the `clean` recipe will be resolved as ` clean`. that is an invalid key in the `recipes` map. the steps have to be trimmed for unnecessary spaces.
