### ISSUE TITLE
ignore failure doesnt work for recipes

### ISSUE THREAD

**Issue by kampanosg** [kampanosg/bakery#38]
the ignore failure feature doesn't work for recipes. For example

```yaml
recipes:
  clean:
    steps:
      - rm -rf appp
  build:
    steps:
      - ^ clean
      - go build -o app *.go
```

the above will still fail since once the `runSteps` function is executed it doesn't have the context that this step should not fail. there has to be a way to pass the `ignoreFail` flag in the recursion
