### ISSUE TITLE
parse variables from YAML

### ISSUE THREAD

**Issue by kampanosg** [kampanosg/bakery#4]
allow users to define a `variables` list which then can be used by the `recipes` or even other `vars`. example syntax:

```yaml
variables:
    - x: eggs
    - y: 42
    - z: "we need :y: of :x:"
    - b: true
```

the runner (#10) should also be able to parse the variables. If one is found, the step has to be adjusted.

<b>acceptance criteria</b>
<ul>
<li>parse the `variables` array as defined above</li>
<li>allow for basic primitives such as `string`, `int` and `bool`</li>
<li>allow for variables to call other variables</li>
<li>runner should read the variables</li>
</ul>
