### ISSUE TITLE
recipe visibility

### ISSUE THREAD

**Issue by kampanosg** [kampanosg/bakery#44]
allow users to mark recipes as `private`. these should not be able to be called directly from the command line. instead they should only be called by other recipes. by default, visibility should be `public`

example syntax:
```yaml
recipes:
  clean:
    private: true
    steps:
      - "rm -rf folder"
```
