### ISSUE TITLE
environments

### ISSUE THREAD

**Issue by kampanosg** [kampanosg/bakery#45]
add the ability for users to define environment variables. they should be able to add them on a global scope and/or per-recipe. for example:

```yaml
env:
  ENVIRONMENT: prod
recipes:
  run:
    env:
      DRY_RUN: false
    steps:
      - "./app"
  build:
    steps:
      - "go build -o app main.go"
```

in the above example, the `env` will be used by all recipes. however, the `env` in the `run` is exclusive to that recipe only.

finally, users should be able to overwrite `env`. the `env` variables in the recipe should always supersede the global `env`.
