### ISSUE TITLE
parse metadata from YAML

### ISSUE THREAD

**Issue by kampanosg** [kampanosg/bakery#5]
Allow users to define a `metadata` field in their Bakefile. The initial version of `bakery` should be able to read the following fields:

```yaml
metadata:
    authors:
        - "Person 1 <person.1@company.org>"
        - "Person 2 <person.2@company.org>"
    version: v1.0.23
    description: "Bakefile for the awesome-api"
```

<b>Acceptance criteria</b>
<ul>
<li>Parse the `metadata` field as shown above</li>
<li>`bake version` should show the version in the metadata if defined</li>
</ul>
